### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by MrXiaoM** [blank038/ServerMarket#1]
界面部分，items的action建议弄得丰富一点，比如加些玩家执行命令，控制台执行命令什么的，方便服主弄返回主菜单按钮  
这里贴上我的部分代码：(已把 switch 改为 if)  
位于 com.blank038.servermarket.data.gui.MarketContainer.openGui(int);
```java
if(action.toLowerCase().startsWith("player:")) {  
	String cmd = action.substring(7).replace('&', ChatColor.COLOR_CHAR).replace("%player%", clicker.getName());  
	Bukkit.dispatchCommand(clicker, cmd);  
}  
if(action.toLowerCase().startsWith("console:")) {  
	String cmd = action.substring(8).replace('&', ChatColor.COLOR_CHAR).replace("%player%", clicker.getName());  
	Bukkit.dispatchCommand(Bukkit.getConsoleSender(), cmd);  
}
```

补：发现无关紧要的一个bug：你没有给 lang.yml 加上 lack-money 的值

**Comment by blank038** [comment]
已采纳，详情见 ([# 将 PlayerData 键值修改为 UUID 形式](https://github.com/Blank038/ServerMarket/commit/c80e5322d9f4559b7395f5211506961d109392c0#diff-d80fae77257e7abd8a59a0b1291a24a9eb6abb55457249a17ddcc982b6662916R227))
