### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by xiaoluofa** [blank038/ServerMarket#10]
新增点击购买的选项
shift购买容易购买多个商品
![image](https://github.com/blank038/ServerMarket/assets/75927411/ed5ceabb-04fd-4ee9-9ea9-dcf554e16604)
通知卖家购买者是谁
管理模式，可以一键下架商品，拉黑商品

**Comment by MSCMDD** [comment]
还希望可以部分购买，增减购买数量

**Comment by MSCMDD** [comment]
> 还希望可以部分购买，增减购买数量

已经单独发起Issure #20
