### ISSUE TITLE
 use /servermarket open

### ISSUE THREAD

**Issue by M0DSTERX** [blank038/ServerMarket#23]
Players use /servermarket open, nothing appears. How do I increase the permission?

**Comment by blank038** [comment]
1. Players use `/servermarket open`, nothing appears
> The `/servermarket open` command does not respond because the market does not exist.
> You can also use a short command to open the market. Check the `short-command` setting in the market config file for details.
2. How do I increase the permission?
> The market permission can be checked in the `permission` option of the market config file.

If you're unable to resolve this issue, feel free to provide more information for my reference. Thank you.

**Comment by M0DSTERX** [comment]
I can fix it. thank you very much.
