### ISSUE TITLE
Please support thai language in ServerMarket.

### ISSUE THREAD

**Issue by M0DSTERX** [blank038/ServerMarket#24]
Hello

I would like to propose to support Thai language in ServerMarket plugin because there are many players in Thailand who are interested in using this plugin. Adding Thai language will improve the user experience and may increase the number of users.

If there is a way to add this support, such as using translation files or adjusting the code, I would be happy to help.

Thank you for your effort in developing this plugin.

**Comment by blank038** [comment]
Hello,

Thank you for your suggestion and for expressing interest in improving the ServerMarket plugin. Supporting Thai language sounds like a great idea and could definitely enhance the experience for users in Thailand.

We currently support localization through translation files, and we would be happy to collaborate on adding Thai language support. If you'd like, you can contribute by providing translations, and I will assist in integrating them into the plugin.

You can add a language file named `th_TH.yml` at [language](https://github.com/blank038/ServerMarket/tree/master/bukkit/src/main/resources/language) and submit a pull request (PR).
Additionally, you can modify the `language` value in the `config.yml` file to `th_TH` for testing.

I truly appreciate your willingness to help and your kind words about the plugin!

**Comment by M0DSTERX** [comment]
Okay , thank you for your positive response! I'm excited to contribute to the ServerMarket plugin and help improve the experience for Thai users.

I have already created the th_TH.yml translation file and submitted a pull request to add Thai language support. I have also modified the config.yml file to set the language value to th_TH for testing purposes.

Please let me know if you need any further adjustments or if there are any specific translations you would like me to include.

Thank you again for your support and for the opportunity to contribute!

**Comment by blank038** [comment]
close in #25
