### ISSUE TITLE
[功能请求] 允许白送（价格为0）

### ISSUE THREAD

**Issue by MSCMDD** [blank038/ServerMarket#26]
有很多玩家有这个需求，希望上架价格可以为0或者是倒贴钱

![image](https://github.com/user-attachments/assets/93111ab4-55de-4db6-b41b-6ad9c28e07fa)

所以有了这个功能请求：（

**Comment by blank038** [comment]
你好，请尝试将 `price.min` 设置为 0，但请不要设置成负数，避免导致出现 BUG
