### ISSUE TITLE
请求兼容XConomy经济插件，让群组服体验更好

### ISSUE THREAD

**Issue by Naohuah** [blank038/ServerMarket#4]
我发现有跨服功能了，但在两个不同步子服购买商品后，必须到你上架的那个子服别人卖=买的东西所支付的经济才会到你的账号上，而不是跨两个服就可以同步。

**Comment by blank038** [comment]
“在两个不同步子服” 指的是什么不同步呢？是否启用 ServerMarket 的 MySQL 了呢？

**Comment by Naohuah** [comment]
比如,我在A服上架商品,然后玩家0在B服买，此时我在A服没有收到任何消息,我进入B服,插件才提示有人购买了我的商品,此时金钱才会到账，如果我我继续在A服，则没有任何提示，金钱也不会到账，只有进入了其他玩家所在的购买的服才会有提示.

**Comment by Naohuah** [comment]
比如,我在A服上架商品,然后玩家0在B服买，此时我在A服没有收到任何消息,我进入B服,插件才提示有人购买了我的商品,此时金钱才会导致，如果我我继续在A服，则没有任何提示，金钱也不会到账，只有进入了其他玩家所在的购买的服才会有提示.
